test: nr

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,6 +1,10 @@
 #!/bin/sh
 # bin/compile <build-dir> <cache-dir> <env-dir>
 
+BUILD_DIR=$1
+CACHE_DIR=$2
+ENV_DIR=$3
+
 DOWNLOAD_URL="https://download.newrelic.com/infrastructure_agent/binaries/linux/amd64/newrelic-infra_linux_1.59.0_amd64.tar.gz"
 filename="newrelic-infra-binary.tar.gz"
 BUILD_DIR="./"
@@ -12,15 +16,15 @@ tar -zxvf $filename -C $BUILD_DIR
 chmod +x newrelic-infra
 
 # cd "newrelic-infra" || exit
-
+echo "-------------------------------------"
 # Access the license key from the Heroku config var
 NEW_RELIC_LICENSE_KEY="${NEW_RELIC_LICENSE_KEY:-}"
 echo "New Relic License Key: \"$NEW_RELIC_LICENSE_KEY\""
 
 # ls -a
 
-# NEW_RELIC_LICENSE_KEY=$(cat $ENV_DIR/NEW_RELIC_LICENSE_KEY)
-
+NEW_RELIC_LICENSE_KEY=$(cat $ENV_DIR/NEW_RELIC_LICENSE_KEY)
+echo "New Relic License Key: \"$NEW_RELIC_LICENSE_KEY\""
 
 # Check if the license key is set
 # if [ -z "$NEW_RELIC_LICENSE_KEY" ]; then
@@ -28,7 +32,7 @@ echo "New Relic License Key: \"$NEW_RELIC_LICENSE_KEY\""
 #   exit 1
 # fi
 
-if [ -z "$NEW_RELIC_APP_NAME" ]; then
-  echo "Error: NEW_RELIC_LICENSE_KEY config var is not set."
-  exit 1
-fi
+# if [ -z "$NEW_RELIC_APP_NAME" ]; then
+#   echo "Error: NEW_RELIC_LICENSE_KEY config var is not set."
+#   exit 1
+# fi
