test: nr

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -15,24 +15,14 @@ tar -zxvf $filename -C $BUILD_DIR
 
 chmod +x newrelic-infra
 
-# cd "newrelic-infra" || exit
-echo "-------------------------------------"
 # Access the license key from the Heroku config var
-NEW_RELIC_LICENSE_KEY="${NEW_RELIC_LICENSE_KEY:-}"
-echo "New Relic License Key: \"$NEW_RELIC_LICENSE_KEY\""
-
-# ls -a
-
 NEW_RELIC_LICENSE_KEY=$(cat $ENV_DIR/NEW_RELIC_LICENSE_KEY)
-echo "New Relic License Key: \"$NEW_RELIC_LICENSE_KEY\""
+# echo "New Relic License Key: \"$NEW_RELIC_LICENSE_KEY\""
+
+cd "newrelic-infra" || exit
 
 # Check if the license key is set
-# if [ -z "$NEW_RELIC_LICENSE_KEY" ]; then
-#   echo "Error: NEW_RELIC_LICENSE_KEY config var is not set."
-#   exit 1
-# fi
-
-# if [ -z "$NEW_RELIC_APP_NAME" ]; then
-#   echo "Error: NEW_RELIC_LICENSE_KEY config var is not set."
-#   exit 1
-# fi
+if [ -z "$NEW_RELIC_LICENSE_KEY" ]; then
+  echo "Error: NEW_RELIC_LICENSE_KEY config var is not set."
+  exit 1
+fi
